### ISSUE TITLE
Error in get_rule_handler after updating to 1.2

### ISSUE THREAD

**Issue by Luckjanov** [pyeve/cerberus#377] opened 2018-04-13 08:41 UTC
After updating from 1.1 to 1.2 my tests are failing with exception:
```_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.6/site-packages/cerberus/validator.py:877: in validate
    self.__validate_definitions(definitions, field)
/usr/local/lib/python3.6/site-packages/cerberus/validator.py:940: in __validate_definitions
    result = validate_rule(rule)
/usr/local/lib/python3.6/site-packages/cerberus/validator.py:922: in validate_rule
    return validator(definitions.get(rule, None), field, value)
/usr/local/lib/python3.6/site-packages/cerberus/validator.py:1236: in _validate_schema
    self.__validate_schema_mapping(field, schema, value)
/usr/local/lib/python3.6/site-packages/cerberus/validator.py:1247: in __validate_schema_mapping
    if not validator(value, update=self.update, normalize=False):
/usr/local/lib/python3.6/site-packages/cerberus/validator.py:877: in validate
    self.__validate_definitions(definitions, field)
/usr/local/lib/python3.6/site-packages/cerberus/validator.py:940: in __validate_definitions
    result = validate_rule(rule)
/usr/local/lib/python3.6/site-packages/cerberus/validator.py:922: in validate_rule
    return validator(definitions.get(rule, None), field, value)
/usr/local/lib/python3.6/site-packages/cerberus/validator.py:1234: in _validate_schema
    self.__validate_schema_sequence(field, schema, value)
/usr/local/lib/python3.6/site-packages/cerberus/validator.py:1259: in __validate_schema_sequence
    update=self.update, normalize=False)
/usr/local/lib/python3.6/site-packages/cerberus/validator.py:877: in validate
    self.__validate_definitions(definitions, field)
/usr/local/lib/python3.6/site-packages/cerberus/validator.py:940: in __validate_definitions
    result = validate_rule(rule)
/usr/local/lib/python3.6/site-packages/cerberus/validator.py:921: in validate_rule
    validator = self.__get_rule_handler('validate', rule)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cerberus.validator.Validator object at 0x7f94a6315a58>
domain = 'validate', rule = 'id'

    def __get_rule_handler(self, domain, rule):
        methodname = '_{0}_{1}'.format(domain, rule.replace(' ', '_'))
        result = getattr(self, methodname, None)
        if result is None:
            raise RuntimeError("There's no handler for '{}' in the '{}' "
>                              "domain.".format(rule, domain))
E           RuntimeError: There's no handler for 'id' in the 'validate' domain.

/usr/local/lib/python3.6/site-packages/cerberus/validator.py:338: RuntimeError```

I don't know if it has something to do with my schemes. I have only one "id":
"id": {
        "required": True,
        "type": "integer"
    }

**Comment by funkyfuture** [comment] 2018-04-13 08:50
Could you please post a chunk of code that reproduces the error?

**Comment by nicolaiarocci** [comment] 2018-04-13 16:28
Hmm eve is also experiencing some issues on travis now that it is installing cerberus 1.2 on the test box, see https://travis-ci.org/pyeve/eve/jobs/366149694

I don't have time to look into it right now, but a quick experiment of switching back to cerberus 1.1 fixed things.

**Comment by nicolaiarocci** [comment] 2018-04-13 16:36
PS: this is probably a different issue, has to do with type validation which has been touched in 1.2, but I seem to remember that old _type validation was supposed to be deprecated, but still functioning.

**Comment by funkyfuture** [comment] 2018-04-13 17:45
> I seem to remember that old _type validation was supposed to be deprecated, but still functioning.

yep, that should be the [case](https://github.com/pyeve/cerberus/commit/ce1ef4f9ecce7853c903a4eccb4f97a6af16fbb2#diff-795369a6cae83c62a70eafa3d3a1852eR1263). there's also still a [test](https://github.com/pyeve/cerberus/commit/ce1ef4f9ecce7853c903a4eccb4f97a6af16fbb2#diff-079ef8e131d2b73e0c86d271418399cf) with legacy type checks.

i'm deep into something else. but i'll see that i try it on one of my projects. please report back if someone can distill a minimal viable bug reproduction. what worries me most is if there's a bug the test coverage would be 'suboptimal'.

**Comment by funkyfuture** [comment] 2018-04-13 19:38
i had no issue with a dependency upgrade.

**Comment by CJ-Wright** [comment] 2018-04-19 18:49
I have also run into this error. Here is the code I needed to produce it
```python
a = {'_id': 'scopatz',
               'education': [
                   {'begin_year': 2002,
                    'degree': 'B.S. Physics',
                    'end_year': 2006,
                    'institution': 'University of California, Santa Barbara',
                    'location': 'Santa Barbara, CA',
                    'other': [
                        'Graduated with a Major in Physics and a Minor in '
                        'Mathematics']}],
               }

b = {'people': {
        'education': {
            'required': True,
            'schema': {'begin_month': {'required': False, 'type': 'string'},
                       'begin_year': {'required': True, 'type': 'integer'},
                       'degree': {'required': True, 'type': 'string'},
                       'end_month': {'required': False, 'type': 'string'},
                       'end_year': {'required': True, 'type': 'integer'},
                       'gpa': {'required': False, 'type': ('float', 'string')},
                       'institution': {'required': True, 'type': 'string'},
                       'location': {'required': True, 'type': 'string'},
                       'other': {'required': False, 'type': 'string'}},
            'type': 'list'},
                  }}

from cerberus import Validator
v = Validator(b['people'])
v.validate(a)
```

**Comment by funkyfuture** [comment] 2018-04-19 22:45
@CJ-Wright could you please provide a minimum disfunct example and what Python version is used, how Cerberus was installed and the value of cerberus.__version__?

@scopatz a new way to define type constraints was added, but the `list` semantics didn't change.

**Comment by CJ-Wright** [comment] 2018-04-20 01:26
So the example I gave above gives me:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-08251e93dd8b> in <module>()
     28 from cerberus import Validator
     29 v = Validator(b['people'])
---> 30 v.validate(a)

~/mc/envs/regro/lib/python3.6/site-packages/cerberus/validator.py in validate(self, document, schema, update, normalize)
    875             definitions = self.schema.get(field)
    876             if definitions is not None:
--> 877                 self.__validate_definitions(definitions, field)
    878             else:
    879                 self.__validate_unknown_fields(field)

~/mc/envs/regro/lib/python3.6/site-packages/cerberus/validator.py in __validate_definitions(self, definitions, field)
    938             rule = self._remaining_rules.pop(0)
    939             try:
--> 940                 result = validate_rule(rule)
    941                 # TODO remove on next breaking release
    942                 if result:

~/mc/envs/regro/lib/python3.6/site-packages/cerberus/validator.py in validate_rule(rule)
    920         def validate_rule(rule):
    921             validator = self.__get_rule_handler('validate', rule)
--> 922             return validator(definitions.get(rule, None), field, value)
    923 
    924         definitions = self._resolve_rules_set(definitions)

~/mc/envs/regro/lib/python3.6/site-packages/cerberus/validator.py in _validate_schema(self, schema, field, value)
   1232 
   1233         if isinstance(value, Sequence) and not isinstance(value, _str_type):
-> 1234             self.__validate_schema_sequence(field, schema, value)
   1235         elif isinstance(value, Mapping):
   1236             self.__validate_schema_mapping(field, schema, value)

~/mc/envs/regro/lib/python3.6/site-packages/cerberus/validator.py in __validate_schema_sequence(self, field, schema, value)
   1257             schema=schema, allow_unknown=self.allow_unknown)
   1258         validator(dict(((i, v) for i, v in enumerate(value))),
-> 1259                   update=self.update, normalize=False)
   1260 
   1261         if validator._errors:

~/mc/envs/regro/lib/python3.6/site-packages/cerberus/validator.py in validate(self, document, schema, update, normalize)
    875             definitions = self.schema.get(field)
    876             if definitions is not None:
--> 877                 self.__validate_definitions(definitions, field)
    878             else:
    879                 self.__validate_unknown_fields(field)

~/mc/envs/regro/lib/python3.6/site-packages/cerberus/validator.py in __validate_definitions(self, definitions, field)
    938             rule = self._remaining_rules.pop(0)
    939             try:
--> 940                 result = validate_rule(rule)
    941                 # TODO remove on next breaking release
    942                 if result:

~/mc/envs/regro/lib/python3.6/site-packages/cerberus/validator.py in validate_rule(rule)
    919 
    920         def validate_rule(rule):
--> 921             validator = self.__get_rule_handler('validate', rule)
    922             return validator(definitions.get(rule, None), field, value)
    923 

~/mc/envs/regro/lib/python3.6/site-packages/cerberus/validator.py in __get_rule_handler(self, domain, rule)
    336         if result is None:
    337             raise RuntimeError("There's no handler for '{}' in the '{}' "
--> 338                                "domain.".format(rule, domain))
    339         return result
    340 

RuntimeError: There's no handler for 'begin_month' in the 'validate' domain.
```
so I believe that that is dysfunctional. (I presume that's what you meant by "disfunct" although maybe I'm wrong). Feel free to pair it down more but I don't know where the boundary is at this point (and I don't think the example is that unwieldy). 

python:
```
Python 3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:31:06) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
```
Cerberus was installed via the conda-forge package:
`cerberus                  1.2                      py36_0    conda-forge`

```python
import cerberus
cerverus.__version__
```
gave 1.2

**Comment by CJ-Wright** [comment] 2018-04-20 13:53
Git bisect has [this](https://github.com/pyeve/cerberus/commit/6f9300b89d3d1741de97c35fc7bf5e58ba591239) as the commit where the issue started.

**Comment by CJ-Wright** [comment] 2018-04-20 14:27
I was able to find the issue here. The data is a list of dicts, but the schema only had a list level. Changing the schema to be `{'type': 'list', 'schema': {'type': 'dict', 'schema': {...}}}` seemed to fix things.

Would there be any interest in putting something about this in the error or on a gotcha page or in the `schema: dict` docs? It seems like a rough thing to debug and something not caught previously.

**Comment by funkyfuture** [comment] 2018-04-21 14:55
@CJ-Wright thanks for digging. so i assume that the schema was incorrect before and there's a guard against this now? see #385 which addresses this.

@Luckjanov is this the cause for your case too? or what's your status on this issue?

**Comment by nicolaiarocci** [comment] 2018-04-23 08:46
In my case yes, the schema was actually incorrect. Previously, no warning/error was raised by Cerberus, so we didn't really notice the issue. 

Closing the ticket. If @Luckjanov has something different to report we can reopen it.

**Closed by nicolaiarocci** 2018-04-23 08:46 UTC

**Comment by flyte** [comment] 2018-04-30 10:39
I've also got the same issue, and I have to say, it was difficult to debug, given the obscure `RuntimeError: There's no handler for 'src' in the 'validate' domain` exception. Especially since it worked fine before `v1.2`.

This is the code that previously worked but now raises the exception:
```python
from cerberus import Validator


CONFIG_SCHEMA = {
    'templates': dict(
        type='list',
        schema={
            'src': dict(type='string', required=True, empty=False),
        }
    )
}

validator = Validator(CONFIG_SCHEMA)
validator.validate(dict(templates=[dict(src='test')]))
```

However, the fix that worked for @CJ-Wright doesn't seem to for me:

```python
from cerberus import Validator


CONFIG_SCHEMA = {
    'templates': dict(
        type='list',
        schema=dict(
            type='dict',
            schema={
                'src': dict(type='string', required=True, empty=False),
            }
        )
    )
}

validator = Validator(CONFIG_SCHEMA)
validator.validate(dict(templates=[dict(src='test')]))
```
