### ISSUE TITLE
coerce within items doesn't work

### ISSUE THREAD

**Issue by DeepGitz** [pyeve/cerberus#457] opened 2018-12-09 21:42 UTC
Used Cerberus version / latest commit: 1.2
python: 3.7

- [x] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.

- [x] My question does not concern a practical use-case that I can't figure out
      to solve.

#### Bug report / Feature request

In a list of lists, The coerce function doesn't work within 'items'.

The following code should not produce error, but is does, as the 'coerce' is simply ignored.

```python
import cerberus
v = cerberus.Validator()
schema = {'list_of_values': {'type': 'list',
                             'schema': {'items': [{'type': 'string', 'coerce': str},
                                                  {'type': 'integer', 'coerce': int}]}}
                             }
document = {'list_of_values': [['hello', 100], [123, "122"]]}
v.validate(document, schema)
v.errors
}
```
Output:
```
{'list_of_values': [{1: [{0: ['must be of string type'],
     1: ['must be of integer type']}]}]}
```

**Comment by funkyfuture** [comment] 2019-01-03 12:52
this seems to be a duplicate of [this SO question](https://stackoverflow.com/questions/53688770/cerberus-coercion-within-nested-list) where i noted that i cannot reproduce the reported bahviour.

**Closed by funkyfuture** 2019-01-03 12:52 UTC

**Comment by pedro2555** [comment] 2019-03-15 13:04
I've found the SO post first, and also replied there.

@funkyfuture 

I can reproduce the problem on my side, exactly as posted (check the SO post of my console output).

I got to this with a slightly different problem, I need to accept a list of dicts, and then coerce such dicts into a more complete ones. How would one go about doing that?
