### ISSUE TITLE
I18n support

### ISSUE THREAD

**Issue by nykolaslima** [pyeve/cerberus#352] opened 2017-12-06 17:56 UTC
I didn't saw any i18n support in cerberus, it would be nice to have a simple way to customize the validation messages.

**Comment by andreymal** [comment] 2017-12-09 14:31
Duplicate of #174?

I use this workaround: https://github.com/pyeve/cerberus/issues/174#issuecomment-192278848

**Comment by funkyfuture** [comment] 2018-04-12 11:43
this issue can be closed, right?

**Closed** 2018-04-12 12:33 UTC
