### ISSUE TITLE
readonly works properly just in the first validation

### ISSUE THREAD

**Issue by mbarakaja** [pyeve/cerberus#311] opened 2017-04-20 01:22 UTC
Given the next code:

```python
from cerberus import Validator


v = Validator({
    'id': {'type': 'integer', 'readonly': True},
})


v.validate({'id': 1}) # False
v.validate({'id': 1}) # True
v.validate({'id': 1}) # True
v.validate({'id': 1}) # True
```

Just the first call validates correctly and return `False`. The subsequent calls to `validate(...)` return True. This just happen to me with property `readonly`. It looks like the validation works just on time.

**Is this an intentional behavior of this library?**

**Comment by funkyfuture** [comment] 2017-04-21 11:01
what is `v.errors` after the first call?

**Comment by mbarakaja** [comment] 2017-04-21 11:56
The first call sets `v.errors` to `{'id': ['field is read-only']}`. Subsecuent calls set it to an empty dictionary `{}`.

**Comment by funkyfuture** [comment] 2017-04-21 13:15
just scratching at the surface, and i'm pretty sure that is caused by the `readonly` / `default` thing. 

i changed `is_normalized` to a private property in order to not get it inherited by child-validators and made it being set and unset cosistently. that solve this issue, but breaks `test_nested_readonly_field_with_default_value`. cc @dkellner 

@nicolaiarocci thus i'd say this is a show-stopper for a 1.2 release.

my tinkering so far:

```diff
diff --git a/cerberus/tests/test_validation.py b/cerberus/tests/test_validation.py
index ec97de5..155c89b 100644
--- a/cerberus/tests/test_validation.py
+++ b/cerberus/tests/test_validation.py
@@ -145,6 +145,13 @@ def test_nested_readonly_field_with_default_value():
                 schema, errors=expected_errors)
 
 
+def test_repeated_readonly(validator):
+    # https://github.com/pyeve/cerberus/issues/311
+    validator.schema = {'id': {'readonly': True}}
+    assert_fail({'id': 0}, validator=validator)
+    assert_fail({'id': 0}, validator=validator)
+
+
 def test_not_a_string():
     assert_bad_type('a_string', 'string', 1)
 
diff --git a/cerberus/validator.py b/cerberus/validator.py
index f28f74c..b8edca7 100644
--- a/cerberus/validator.py
+++ b/cerberus/validator.py
@@ -410,14 +410,14 @@ class Validator(object):
         Type: :class:`bool` """
         return self._config.get('is_child', False)
 
-    @property
-    def is_normalized(self):
-        """ ``True`` if the document is already normalized. """
-        return self._config.get('is_normalized', False)
-
-    @is_normalized.setter
-    def is_normalized(self, value):
-        self._config['is_normalized'] = value
+    # @property
+    # def is_normalized(self):
+    #     """ ``True`` if the document is already normalized. """
+    #     return self._config.get('is_normalized', False)
+    #
+    # @is_normalized.setter
+    # def is_normalized(self, value):
+    #     self._config['is_normalized'] = value
 
     @property
     def purge_unknown(self):
@@ -548,6 +548,7 @@ class Validator(object):
             return self.document
 
     def __normalize_mapping(self, mapping, schema):
+        self._is_normalized = False
         if isinstance(schema, _str_type):
             schema = self._resolve_schema(schema)
         schema = schema.copy()
@@ -564,6 +565,7 @@ class Validator(object):
         self.__normalize_default_fields(mapping, schema)
         self._normalize_coerce(mapping, schema)
         self.__normalize_containers(mapping, schema)
+        self._is_normalized = True
         return mapping
 
     def _normalize_coerce(self, mapping, schema):
@@ -816,7 +818,8 @@ class Validator(object):
         self.__init_processing(document, schema)
         if normalize:
             self.__normalize_mapping(self.document, self.schema)
-            self.is_normalized = True
+        else:
+            self._is_normalized = False
 
         for field in self.document:
             if self.ignore_none_values and self.document[field] is None:
@@ -1113,7 +1116,7 @@ class Validator(object):
     def _validate_readonly(self, readonly, field, value):
         """ {'type': 'boolean'} """
         if readonly:
-            if not self.is_normalized:
+            if not self._is_normalized:
                 self._error(field, errors.READONLY_FIELD)
             # If the document was normalized (and therefore already been
             # checked for readonly fields), we still have to return True
@@ -1121,7 +1124,7 @@ class Validator(object):
             has_error = errors.READONLY_FIELD in \
                 self.document_error_tree.fetch_errors_from(
                     self.document_path + (field,))
-            if self.is_normalized and has_error:
+            if self._is_normalized and has_error:
                 self._drop_remaining_rules()
 
     def _validate_regex(self, pattern, field, value):
```

**Comment by funkyfuture** [comment] 2017-05-02 10:37
@nicolaiarocci can you please add a bug label and assign this issue to the 1.2 milestone? i'm in fear it may be forgotten otherwise as there has been no feedback so far.

**Comment by nicolaiarocci** [comment] 2017-05-02 12:24
yeah sorry about that

**Comment by dkellner** [comment] 2017-05-07 04:07
I'll look into this. The main reason for this is that we're treating `readonly` as a normalization rule (and not as other validation rules). My first proposed solution for `default`+`readonly` (https://github.com/pyeve/cerberus/pull/272) does not suffer from this problem.

**Comment by dkellner** [comment] 2017-05-07 04:59
It seems to be enough to reset `is_normalized` when a new document is coming in - all tests are passing now. The fact that this actually was not done before makes me wonder if there exist more bugs because of this. I will investigate further.

@funkyfuture What do you think about this? 

```diff
diff --git a/cerberus/tests/test_validation.py b/cerberus/tests/test_validation.py
index ec97de5..2c31a74 100644
--- a/cerberus/tests/test_validation.py
+++ b/cerberus/tests/test_validation.py
@@ -85,6 +85,13 @@ def test_readonly_field_first_rule():
     assert 'read-only' in v.errors['a_readonly_number'][0]
 
 
+def test_repeated_readonly(validator):
+    # https://github.com/pyeve/cerberus/issues/311
+    validator.schema = {'id': {'readonly': True}}
+    assert_fail({'id': 0}, validator=validator)
+    assert_fail({'id': 0}, validator=validator)
+
+
 def test_readonly_field_with_default_value():
     schema = {
         'created': {
diff --git a/cerberus/validator.py b/cerberus/validator.py
index f28f74c..fd6b6eb 100644
--- a/cerberus/validator.py
+++ b/cerberus/validator.py
@@ -492,6 +492,8 @@ class Validator(object):
         self.document_error_tree = errors.DocumentErrorTree()
         self.schema_error_tree = errors.SchemaErrorTree()
         self.document = copy(document)
+        if not self.is_child:
+            self.is_normalized = False
 
         if schema is not None:
             self.schema = DefinitionSchema(self, schema)
```

**Closed** 2017-05-13 06:58 UTC
Labels: bug
