### ISSUE TITLE
install_requires=["setuptools"], in setup.py is wrong

### ISSUE THREAD

**Issue by socketpair** [pyeve/cerberus#596] opened 2023-01-14 19:40 UTC
Actually, `setuptools` is dev-requirement. It's required only to build the package.

It's not required for Cerberus to work when it is installed.

Please remove this from requirements becuse it adds extra packaes in target systems. For example, Fedora's `python3-cerberus` depends on `python3-setuptools`, which is very bad.

**Comment by socketpair** [comment] 2023-01-14 20:35
I figured out.

`cerberus/__init__.py` contains code:

```python
try:
    __version__ = get_distribution("Cerberus").version
except DistributionNotFound:
    __version__ = "unknown"
```

It's painfully slow (200 ms) on systems where many packages installed. This place needs to be patched.

**Comment by socketpair** [comment] 2023-01-14 20:36
https://github.com/skorokithakis/shortuuid/issues/59 same shit

pkg_resources is  deprecated

please either remove dynamic `__version__` setup (better) or change to `importlib.metadata`

**Comment by socketpair** [comment] 2023-01-14 20:40
https://github.com/pypa/setuptools/issues/926

**Comment by funkyfuture** [comment] 2023-01-16 13:00
thanks, this is a duplicate of #579

**Closed as completed by funkyfuture** 2023-01-16 13:00 UTC
