### ISSUE TITLE
Segmentation Fault when constructing a validator from schema

### ISSUE THREAD

**Issue by zhangtemplar** [pyeve/cerberus#473] opened 2019-03-14 01:01 UTC
More background in this [eve bug 1221](https://github.com/pyeve/eve/issues/1221)

The minimal example can be found in [minimal failing schema](https://github.com/pyeve/eve/issues/1221#issuecomment-472280945)

Also it only crashes on (every docker) container but not my host machine.

**Comment by zhangtemplar** [comment] 2019-03-14 01:02
Probably related to #176

**Comment by zhangtemplar** [comment] 2019-03-14 03:27
Just check set recursion limit from 1000 to 3000 (my host machine is using this and the eve doesn't crash with it) doesn't solve the problem.

**Comment by zhangtemplar** [comment] 2019-03-14 04:22
I think cerberus is not very robust in handling the dict nested in list, which is nested in another dict.

**Comment by funkyfuture** [comment] 2019-03-14 11:58
please post a unit test to let us reproduce what you report. your example looks like it could be reduced, there's also no test data and it's unlcear what the `data_relation` is.

> Also it only crashes on (every docker) container but not my host machine.

that points to a problem with the interpreter. the repository also contains a script to run the test suite in a Docker container.

**Comment by zhangtemplar** [comment] 2019-03-26 23:35
@funkyfuture thanks for the reply. Here is the schema that should cause the crash:

```
{
  'type': 'dict',
  'required': True,
  'schema': {
    'name': {'type': 'string', 'required': True},
    'course': {
      'type': 'dict',
      'required': True,
      'schema': {
        'public': {'type': 'boolean', 'required': False, 'default': False},
        'lesson': {
          'type': 'list',
          'required': True,
          'schema': {
            'type': 'object',
            'required': True,
            'schema': {
              'name': {'type': 'string', 'required': True},
              'url': {'type': 'string', 'required': True},
              'abs': {'type': 'string', 'required' False, 'default': ''},
              'public': {'type': 'string', 'required': False, 'default': False},
            }
          }
        }
      }
    } 
  }
}
```

**Comment by funkyfuture** [comment] 2019-08-08 15:02
could you please provide an image that allows to reproduce the bug?

**Comment by funkyfuture** [comment] 2021-03-27 18:56
i'm closing this as the bug can't be reproduced.

**Closed by funkyfuture** 2021-03-27 18:56 UTC
